import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { storeTemplates, getStoreBySlug } from "@/content/gallery";
import { storeThemes } from "@/content/store-themes";
import { Storefront } from "@/components/store/storefront";

type Params = { params: Promise<{ slug: string }> };

export function generateStaticParams() {
  return storeTemplates.map((s) => ({ slug: s.slug }));
}

export async function generateMetadata({ params }: Params): Promise<Metadata> {
  const { slug } = await params;
  const store = getStoreBySlug(slug);
  if (!store) return { title: "Store not found" };
  return {
    title: `${store.name} — ${store.category} Store Demo`,
    description: `${store.tagline}. A live storefront demo generated by EcomStrait.`,
  };
}

export default async function StorePage({ params }: Params) {
  const { slug } = await params;
  const store = getStoreBySlug(slug);
  const theme = storeThemes[slug];
  if (!store || !theme) notFound();
  return <Storefront store={store} theme={theme} />;
}
