import "server-only";
import type { PlanSection, StorePlan } from "@/lib/ecomai";

/**
 * Render a store's content blocks into Liquid.
 *
 * Shopify themes are static packages and Liquid can't parse arbitrary JSON, so
 * a merchant's freeform sections can't be expressed as theme settings. What we
 * can do is generate the markup: every store gets its own copy of the theme
 * files at upload time, so `sections/custom-content.liquid` is written per
 * store with that store's blocks already rendered.
 *
 * The output is plain HTML using the classes each theme's stylesheet defines,
 * which keeps a Forge store looking like Forge without six variants of this.
 */

/** The one theme file the builder generates per store. */
export const CUSTOM_CONTENT_FILE = "sections/custom-content.liquid";

/** Liquid delimiters in merchant copy would execute; HTML entities would not. */
function esc(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/\{\{/g, "&#123;&#123;")
    .replace(/\{%/g, "&#123;%");
}

function heading(section: PlanSection): string {
  const h = section.heading?.trim();
  return h ? `    <h2 class="es-block__heading">${esc(h)}</h2>\n` : "";
}

function renderSection(section: PlanSection): string {
  const body = section.body?.trim();
  const media = section.media ?? [];
  const items = section.items ?? [];
  if (!section.heading?.trim() && !body && !media.length && !items.length) return "";

  let inner = "";

  switch (section.type) {
    case "features":
      if (items.length) {
        inner =
          `    <div class="es-grid es-grid--3">\n` +
          items
            .map(
              (i) =>
                `      <div><h3>${esc(i.title)}</h3><p class="muted">${esc(i.description)}</p></div>`,
            )
            .join("\n") +
          `\n    </div>\n`;
      }
      break;

    case "gallery":
      if (media.length) {
        inner =
          `    <div class="es-grid es-grid--4">\n` +
          media
            .map(
              (m) =>
                `      <img class="es-media es-media--square" src="${esc(m.url)}" alt="${esc(m.alt ?? "")}" loading="lazy" width="800" height="800">`,
            )
            .join("\n") +
          `\n    </div>\n`;
      }
      break;

    case "video":
      if (media[0]) {
        inner =
          `    <video class="es-media" src="${esc(media[0].url)}" controls playsinline></video>\n` +
          (body ? `    <p class="es-block__body muted">${esc(body)}</p>\n` : "");
      }
      break;

    case "image":
      if (media[0]) {
        inner =
          `    <div class="es-grid es-split">\n` +
          `      <img class="es-media" src="${esc(media[0].url)}" alt="${esc(media[0].alt ?? "")}" loading="lazy" width="1200" height="800">\n` +
          (body ? `      <p>${esc(body)}</p>\n` : "") +
          `    </div>\n`;
      }
      break;

    default:
      if (body) inner = `    <p class="es-block__body">${esc(body)}</p>\n`;
  }

  if (!inner && !section.heading?.trim()) return "";

  return `  <section class="es-block">\n    <div class="container">\n${heading(section)}${inner}    </div>\n  </section>\n`;
}

const SCHEMA = `
{% schema %}
{
  "name": "Custom content",
  "settings": [],
  "presets": [{ "name": "Custom content" }]
}
{% endschema %}
`;

const BANNER = `{% comment %}
  Generated by the EcomStrait builder. Edits here are overwritten on the
  next sync — change the content in your dashboard instead.
{% endcomment %}`;

/**
 * The `sections/custom-content.liquid` body for a plan.
 *
 * Always returns a complete section file, including when the merchant has no
 * blocks — an empty one is what removes blocks they deleted. Returning the
 * package's placeholder only on the way in would leave stale markup on a live
 * theme, since the re-sync overwrites this file rather than diffing it.
 */
export function customContentSection(plan: Pick<StorePlan, "sections"> | null): string {
  const rendered = (plan?.sections ?? []).map(renderSection).filter(Boolean).join("\n");
  return `${BANNER}\n\n${rendered}${SCHEMA}`;
}

/**
 * The theme files for a store: the base package, with its custom-content
 * section replaced by this store's blocks.
 */
export function themeFilesWithContent(
  files: Record<string, string>,
  plan: Pick<StorePlan, "sections"> | null,
): Record<string, string> {
  return { ...files, [CUSTOM_CONTENT_FILE]: customContentSection(plan) };
}
