import { ArrowRight } from "lucide-react";
import { Section, SectionHeading } from "@/components/ui/section";
import { Button } from "@/components/ui/button";
import { StoreGallery } from "@/components/shared/store-gallery";

export function StoreGallerySection() {
  return (
    <Section tone="muted" id="gallery">
      <SectionHeading
        eyebrow="Store Gallery"
        title="Real stores, generated by AI"
        description="Browse a few of the storefronts EcomStrait can build for you across every category — each fully responsive, on-brand, and ready to sell."
      />
      <div className="mt-14">
        <StoreGallery limit={8} />
      </div>
      <div className="mt-10 flex justify-center">
        <Button href="/store-gallery" variant="secondary" size="md">
          View the full gallery <ArrowRight className="h-4 w-4" />
        </Button>
      </div>
    </Section>
  );
}
