"use client";

import { ArrowRight, Sparkles } from "lucide-react";
import { useReducedMotion } from "framer-motion";
import { Section, SectionHeading } from "@/components/ui/section";
import { Button } from "@/components/ui/button";
import { Reveal } from "@/components/ui/reveal";
import { StoreGallery } from "@/components/shared/store-gallery";

export function StoreGallerySection() {
  const reduce = useReducedMotion();

  return (
    <Section tone="muted" id="gallery">
      <style>{`@keyframes gallery-shimmer { to { background-position: 200% center; } }`}</style>
      <SectionHeading
        eyebrow="Store Gallery"
        title="Real stores, generated by AI"
        description="Browse a few of the storefronts EcomStrait can build for you across every category — each fully responsive, on-brand, and ready to sell."
      />

      {/* Live "AI-generated" shimmer badge */}
      <Reveal className="mt-6 flex justify-center" delay={1}>
        <span className="inline-flex items-center gap-2 rounded-full border border-ai-100 bg-white px-3.5 py-1.5 text-xs font-semibold shadow-sm">
          <Sparkles className="h-3.5 w-3.5 text-ai-500" />
          <span
            className="bg-clip-text text-transparent"
            style={{
              backgroundImage:
                "linear-gradient(100deg, #3b82f6, #10b981, #3b82f6)",
              backgroundSize: "200% auto",
              color: reduce ? "#3b82f6" : undefined,
              animation: reduce ? undefined : "gallery-shimmer 4s linear infinite",
            }}
          >
            AI-generated in real time
          </span>
          <span className="relative flex h-1.5 w-1.5">
            {!reduce && (
              <span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-brand-500 opacity-70" />
            )}
            <span className="relative inline-flex h-1.5 w-1.5 rounded-full bg-brand-500" />
          </span>
        </span>
      </Reveal>

      <div className="mt-14">
        <StoreGallery filterable limit={8} />
      </div>
      <div className="mt-10 flex justify-center">
        <Button href="/store-gallery" variant="secondary" size="md">
          View the full gallery <ArrowRight className="h-4 w-4" />
        </Button>
      </div>
    </Section>
  );
}
