"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import {
  ShoppingBag, Search, Heart, Star, Truck, ShieldCheck, RefreshCw,
  ArrowRight, ArrowLeft, Sparkles, X,
} from "lucide-react";
import type { StoreTemplate } from "@/content/gallery";
import { collectionsOf, type Product, type StoreTheme } from "@/content/store-themes";

const FEATURE_ICONS = [Truck, ShieldCheck, RefreshCw];

/** Deterministic asset filename — matches the provided asset list. */
export function slugify(s: string): string {
  return s
    .toLowerCase()
    .normalize("NFKD")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

/**
 * A complete, interactive one-page storefront demo — themed by the store's
 * accent + gradient. Real photos load from /store/<slug>/…; until they exist,
 * a category emoji shows in their place (so it always looks intentional).
 */
export function Storefront({
  store,
  theme,
}: {
  store: StoreTemplate;
  theme: StoreTheme;
}) {
  const { accent } = store;
  const [g0, g1] = store.gradient;
  const collections = useMemo(() => collectionsOf(theme), [theme]);

  const [active, setActive] = useState<string>("All");
  const [query, setQuery] = useState("");
  const [searchOpen, setSearchOpen] = useState(false);

  const visible = useMemo(() => {
    const q = query.trim().toLowerCase();
    if (q) return theme.products.filter((p) => p.name.toLowerCase().includes(q));
    if (active === "All") return theme.products;
    return theme.products.filter((p) => p.collection === active);
  }, [theme.products, active, query]);

  function selectCollection(c: string) {
    setActive(c);
    setQuery("");
    setSearchOpen(false);
    const el = document.getElementById("products");
    if (el) el.scrollIntoView({ behavior: "smooth", block: "start" });
  }

  const heroBase = `/store/${store.slug}/hero`;

  return (
    <div className="min-h-screen bg-white text-ink-950">
      <style>{`@keyframes sf-fade{from{opacity:0}to{opacity:1}}`}</style>
      {/* ---- Demo ribbon ---- */}
      <div className="flex items-center justify-center gap-2 bg-ink-950 px-4 py-2 text-center text-[12px] text-white/80">
        <Sparkles className="h-3.5 w-3.5" style={{ color: accent }} />
        <span>Live demo store generated by <span className="font-semibold text-white">EcomStrait</span></span>
        <Link href="/store-owners" className="font-semibold underline decoration-white/30 underline-offset-2 hover:text-white">
          Build one like it →
        </Link>
      </div>

      {/* ---- Promo bar ---- */}
      <div className="px-4 py-2 text-center text-sm font-medium text-white" style={{ background: accent }}>
        {theme.promo}
      </div>

      {/* ---- Nav ---- */}
      <header className="sticky top-0 z-40 border-b border-ink-100 bg-white/85 backdrop-blur">
        <div className="mx-auto flex max-w-6xl items-center justify-between gap-4 px-5 py-4 sm:px-8">
          <button onClick={() => selectCollection("All")} className="text-xl font-extrabold tracking-tight" style={{ color: accent }}>
            {store.name}
          </button>
          <nav className="hidden items-center gap-6 text-sm font-medium text-ink-600 md:flex">
            {collections.map((c) => (
              <button
                key={c}
                onClick={() => selectCollection(c)}
                className="relative py-1 transition-colors hover:text-ink-950"
                style={active === c && !query ? { color: accent } : undefined}
              >
                {c}
                {active === c && !query && (
                  <span className="absolute inset-x-0 -bottom-0.5 h-0.5 rounded-full" style={{ background: accent }} />
                )}
              </button>
            ))}
          </nav>
          <div className="flex items-center gap-1.5 text-ink-700">
            <button aria-label="Search" onClick={() => setSearchOpen((s) => !s)} className="grid h-9 w-9 place-items-center rounded-full transition-colors hover:bg-ink-50">
              {searchOpen ? <X className="h-[18px] w-[18px]" /> : <Search className="h-[18px] w-[18px]" />}
            </button>
            <button aria-label="Wishlist" className="hidden h-9 w-9 place-items-center rounded-full transition-colors hover:bg-ink-50 sm:grid">
              <Heart className="h-[18px] w-[18px]" />
            </button>
            <button aria-label="Cart" className="relative grid h-9 w-9 place-items-center rounded-full transition-colors hover:bg-ink-50">
              <ShoppingBag className="h-[18px] w-[18px]" />
              <span className="absolute -right-0.5 -top-0.5 grid h-4 w-4 place-items-center rounded-full text-[10px] font-bold text-white" style={{ background: accent }}>2</span>
            </button>
          </div>
        </div>
        {/* search row */}
        {searchOpen && (
          <div className="border-t border-ink-100 bg-white">
            <div className="mx-auto flex max-w-6xl items-center gap-2 px-5 py-3 sm:px-8">
              <Search className="h-4 w-4 text-ink-400" />
              <input
                autoFocus
                value={query}
                onChange={(e) => setQuery(e.target.value)}
                placeholder={`Search ${store.name}…`}
                aria-label="Search products"
                className="h-8 flex-1 bg-transparent text-sm outline-none placeholder:text-ink-400"
              />
            </div>
          </div>
        )}
      </header>

      {/* ---- Hero ---- */}
      {theme.variant === "spotlight" ? (
        <HeroSpotlight store={store} theme={theme} heroBase={heroBase} onShop={() => selectCollection("All")} />
      ) : (
        <HeroSplit store={store} theme={theme} heroBase={heroBase} onShop={() => selectCollection("All")} />
      )}

      {/* ---- Products ---- */}
      <section id="products" className="mx-auto max-w-6xl scroll-mt-20 px-5 py-16 sm:px-8">
        <div className="mb-8 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between">
          <div>
            <p className="text-xs font-bold uppercase tracking-[0.16em]" style={{ color: accent }}>Shop</p>
            <h2 className="mt-1 text-3xl font-bold tracking-tight text-ink-950">
              {query ? `Results for “${query}”` : active === "All" ? "Bestsellers this week" : active}
            </h2>
          </div>
          {/* collection filter chips */}
          <div className="no-scrollbar -mx-1 flex gap-2 overflow-x-auto px-1 pb-1">
            {["All", ...collections].map((c) => {
              const on = active === c && !query;
              return (
                <button
                  key={c}
                  onClick={() => selectCollection(c)}
                  className="whitespace-nowrap rounded-full border px-3.5 py-1.5 text-sm font-medium transition-colors"
                  style={
                    on
                      ? { background: accent, borderColor: accent, color: "#fff" }
                      : { borderColor: "var(--color-ink-200)", color: "var(--color-ink-600)" }
                  }
                >
                  {c}
                </button>
              );
            })}
          </div>
        </div>

        {visible.length === 0 ? (
          <p className="rounded-2xl border border-dashed border-ink-200 py-16 text-center text-ink-400">
            No products found. <button onClick={() => selectCollection("All")} className="font-semibold" style={{ color: accent }}>View all →</button>
          </p>
        ) : (
          <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">
            {visible.map((p) => (
              <ProductCard key={p.name} product={p} slug={store.slug} accent={accent} gradient={[g0, g1]} />
            ))}
          </div>
        )}
      </section>

      {/* ---- Features ---- */}
      <section id="story" className="border-y border-ink-100 bg-ink-50/60">
        <div className="mx-auto grid max-w-6xl gap-6 px-5 py-14 sm:grid-cols-3 sm:px-8">
          {theme.features.map((f, i) => {
            const Icon = FEATURE_ICONS[i % FEATURE_ICONS.length];
            return (
              <div key={f.title} className="flex items-start gap-4">
                <span className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl" style={{ background: `${accent}18`, color: accent }}>
                  <Icon className="h-6 w-6" />
                </span>
                <div>
                  <h3 className="font-bold text-ink-950">{f.title}</h3>
                  <p className="mt-1 text-sm leading-relaxed text-ink-500">{f.description}</p>
                </div>
              </div>
            );
          })}
        </div>
      </section>

      {/* ---- Quote ---- */}
      <section className="mx-auto max-w-3xl px-5 py-20 text-center sm:px-8">
        <span className="flex justify-center" style={{ color: accent }}>
          {Array.from({ length: 5 }).map((_, i) => <Star key={i} className="h-5 w-5 fill-current" />)}
        </span>
        <blockquote className="mt-5 text-2xl font-semibold leading-snug tracking-tight text-ink-950 sm:text-3xl">
          “{theme.quote.text}”
        </blockquote>
        <p className="mt-4 text-sm font-medium text-ink-500">— {theme.quote.author}, verified buyer</p>
      </section>

      {/* ---- Newsletter ---- */}
      <section className="px-5 pb-20 sm:px-8">
        <div className="mx-auto max-w-4xl overflow-hidden rounded-3xl px-6 py-12 text-center sm:px-12" style={{ background: `linear-gradient(135deg, ${accent}, ${accent}cc)` }}>
          <h2 className="text-2xl font-bold text-white sm:text-3xl">Join the {store.name} club</h2>
          <p className="mx-auto mt-2 max-w-md text-white/80">Get 10% off your first order plus early access to new drops.</p>
          <form className="mx-auto mt-6 flex max-w-md flex-col gap-3 sm:flex-row" onSubmit={(e) => e.preventDefault()}>
            <input type="email" placeholder="Enter your email" aria-label="Email address" className="h-12 flex-1 rounded-full border-0 bg-white/95 px-5 text-sm text-ink-950 outline-none placeholder:text-ink-400" />
            <button type="submit" className="h-12 rounded-full bg-ink-950 px-6 text-sm font-semibold text-white transition-colors hover:bg-ink-800">Subscribe</button>
          </form>
        </div>
      </section>

      {/* ---- Footer ---- */}
      <footer className="border-t border-ink-100 bg-white">
        <div className="mx-auto flex max-w-6xl flex-col items-center justify-between gap-4 px-5 py-8 text-sm text-ink-500 sm:flex-row sm:px-8">
          <span className="font-extrabold tracking-tight" style={{ color: accent }}>{store.name}</span>
          <span>© {store.name}. A demo storefront.</span>
          <Link href="/" className="inline-flex items-center gap-1.5 font-medium text-ink-700 hover:text-ink-950">
            <ArrowLeft className="h-4 w-4" /> Back to EcomStrait
          </Link>
        </div>
        <div className="bg-ink-950 py-3 text-center text-xs text-white/60">
          Powered by <Link href="/" className="font-semibold text-white hover:underline">EcomStrait</Link> — launch a store like this in hours.
        </div>
      </footer>
    </div>
  );
}

/* ------------------------------------------------------------------ */
/*  Image with emoji fallback                                          */
/* ------------------------------------------------------------------ */

/** Candidate extensions tried in order — supports whatever format the asset
 *  is actually saved as (matched by its real file extension). */
const IMG_EXTS = [".jpg", ".jpeg", ".png", ".webp", ".avif"];

/** Preflight each extension with a throwaway Image; return the one that loads
 *  (or null). The probe warms the cache, so the real <img> paints instantly. */
function useResolvedImage(base: string): string | null {
  const [resolved, setResolved] = useState<string | null>(null);
  useEffect(() => {
    let cancelled = false;
    let idx = 0;
    const tryNext = () => {
      if (cancelled || idx >= IMG_EXTS.length) return;
      const candidate = `${base}${IMG_EXTS[idx++]}`;
      const probe = new window.Image();
      probe.onload = () => {
        if (!cancelled) setResolved(candidate);
      };
      probe.onerror = tryNext;
      probe.src = candidate;
    };
    tryNext();
    return () => {
      cancelled = true;
    };
  }, [base]);
  return resolved;
}

function Media({
  srcBase,
  emoji,
  alt,
  gradient,
  size,
  rounded,
}: {
  srcBase: string;
  emoji: string;
  alt: string;
  gradient: [string, string];
  size: string;
  rounded: string;
}) {
  const resolved = useResolvedImage(srcBase);
  return (
    <div
      className={`relative grid place-items-center overflow-hidden ${rounded}`}
      style={{ background: `linear-gradient(135deg, ${gradient[0]}, ${gradient[1]})` }}
    >
      <span className={`${size} select-none`} aria-hidden>{emoji}</span>
      {resolved && (
        // eslint-disable-next-line @next/next/no-img-element
        <img
          src={resolved}
          alt={alt}
          className="absolute inset-0 h-full w-full object-cover"
          style={{ animation: "sf-fade 0.5s ease" }}
        />
      )}
    </div>
  );
}

/** Full-bleed background photo that fades in over whatever sits behind it. */
function BgImage({ srcBase, alt }: { srcBase: string; alt: string }) {
  const resolved = useResolvedImage(srcBase);
  if (!resolved) return null;
  return (
    // eslint-disable-next-line @next/next/no-img-element
    <img
      src={resolved}
      alt={alt}
      aria-hidden
      className="pointer-events-none absolute inset-0 h-full w-full object-cover"
      style={{ animation: "sf-fade 0.7s ease" }}
    />
  );
}

/* ------------------------------------------------------------------ */
/*  Product card                                                       */
/* ------------------------------------------------------------------ */

function ProductCard({
  product,
  slug,
  accent,
  gradient,
}: {
  product: Product;
  slug: string;
  accent: string;
  gradient: [string, string];
}) {
  const srcBase = `/store/${slug}/${slugify(product.name)}`;
  return (
    <div className="group flex flex-col overflow-hidden rounded-2xl border border-ink-100 bg-white transition-all duration-300 hover:-translate-y-1 hover:shadow-xl hover:shadow-ink-950/5">
      <div className="relative">
        <Media srcBase={srcBase} emoji={product.emoji} alt={product.name} gradient={gradient} size="text-6xl" rounded="aspect-[4/3] w-full" />
        {product.tag && (
          <span className="absolute left-3 top-3 rounded-full px-2.5 py-1 text-[11px] font-bold text-white" style={{ background: accent }}>
            {product.tag}
          </span>
        )}
        <button
          aria-label={`Add ${product.name} to cart`}
          className="absolute bottom-3 right-3 grid h-10 w-10 place-items-center rounded-full text-white opacity-0 shadow-lg transition-all duration-300 group-hover:opacity-100"
          style={{ background: accent }}
        >
          <ShoppingBag className="h-4 w-4" />
        </button>
      </div>
      <div className="flex items-center justify-between p-4">
        <div className="min-w-0">
          <p className="truncate text-sm font-semibold text-ink-950">{product.name}</p>
          <div className="mt-0.5 flex items-center gap-1 text-[11px] text-ink-400">
            <Star className="h-3 w-3 fill-current" style={{ color: accent }} /> 4.9 · {product.collection}
          </div>
        </div>
        <span className="shrink-0 text-base font-extrabold" style={{ color: accent }}>{product.price}</span>
      </div>
    </div>
  );
}

/* ------------------------------------------------------------------ */
/*  Hero — split layout (copy + product collage)                      */
/* ------------------------------------------------------------------ */

function HeroSplit({
  store,
  theme,
  heroBase,
  onShop,
}: {
  store: StoreTemplate;
  theme: StoreTheme;
  heroBase: string;
  onShop: () => void;
}) {
  const { accent } = store;
  const [g0, g1] = store.gradient;
  return (
    <section className="relative overflow-hidden">
      {/* Brand gradient base (fallback when there's no hero photo). */}
      <div aria-hidden className="absolute inset-0" style={{ background: `linear-gradient(135deg, ${g0}, ${g1})` }} />
      {/* Full-bleed hero photo — fades in over the gradient once loaded. */}
      <BgImage srcBase={heroBase} alt={`${store.name} hero`} />
      {/* Themed scrim: denser on the left so the copy stays readable, fading
          to near-clear on the right so the hero photo shows through. */}
      <div aria-hidden className="absolute inset-0" style={{ background: `linear-gradient(to right, ${g0}f2 0%, ${g0}b3 34%, ${g1}26 72%, transparent 100%)` }} />
      <div className="relative z-10 mx-auto grid max-w-6xl items-center gap-10 px-5 py-16 sm:px-8 sm:py-24 lg:grid-cols-2">
        <HeroCopy store={store} theme={theme} onShop={onShop} align="left" />
        <div className="relative hidden lg:block">
          <div className="grid grid-cols-2 gap-4">
            {theme.products.slice(0, 4).map((p, i) => (
              <div key={p.name} className={`overflow-hidden rounded-3xl bg-white/70 p-4 shadow-xl shadow-ink-950/5 backdrop-blur ${i % 2 === 1 ? "translate-y-6" : ""}`}>
                <Media srcBase={`/store/${store.slug}/${slugify(p.name)}`} emoji={p.emoji} alt={p.name} gradient={[`${accent}18`, `${accent}33`]} size="text-5xl" rounded="aspect-square rounded-2xl" />
                <p className="mt-3 truncate text-sm font-semibold text-ink-950">{p.name}</p>
                <p className="text-sm font-bold" style={{ color: accent }}>{p.price}</p>
              </div>
            ))}
          </div>
        </div>
      </div>
    </section>
  );
}

/* ------------------------------------------------------------------ */
/*  Hero — spotlight layout (centered medallion)                      */
/* ------------------------------------------------------------------ */

function HeroSpotlight({
  store,
  theme,
  heroBase,
  onShop,
}: {
  store: StoreTemplate;
  theme: StoreTheme;
  heroBase: string;
  onShop: () => void;
}) {
  const { accent } = store;
  return (
    <section className="relative overflow-hidden" style={{ background: `linear-gradient(180deg, ${store.gradient[0]}, ${store.gradient[1]})` }}>
      <div className="mx-auto flex max-w-3xl flex-col items-center px-5 py-16 text-center sm:px-8 sm:py-24">
        {/* medallion */}
        <div className="relative mb-8">
          <div className="absolute inset-0 -z-0 rounded-full blur-2xl" style={{ background: `${accent}44`, transform: "scale(1.15)" }} />
          <Media srcBase={heroBase} emoji={theme.heroEmoji} alt={store.name} gradient={["#ffffffcc", "#ffffff88"]} size="text-6xl sm:text-7xl" rounded="relative h-40 w-40 rounded-full border-4 border-white/70 shadow-2xl sm:h-52 sm:w-52" />
        </div>
        <HeroCopy store={store} theme={theme} onShop={onShop} align="center" />
        {/* product chips row */}
        <div className="no-scrollbar mt-10 flex w-full justify-start gap-3 overflow-x-auto pb-2 sm:justify-center">
          {theme.products.slice(0, 5).map((p) => (
            <div key={p.name} className="flex shrink-0 items-center gap-2 rounded-full bg-white/70 px-3 py-1.5 text-sm shadow-sm backdrop-blur">
              <span aria-hidden>{p.emoji}</span>
              <span className="font-medium text-ink-800">{p.name.split(" ").slice(0, 2).join(" ")}</span>
              <span className="font-bold" style={{ color: accent }}>{p.price}</span>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

function HeroCopy({
  store,
  theme,
  onShop,
  align,
}: {
  store: StoreTemplate;
  theme: StoreTheme;
  onShop: () => void;
  align: "left" | "center";
}) {
  const { accent } = store;
  const centered = align === "center";
  return (
    <div className={centered ? "flex flex-col items-center" : ""}>
      <span className="inline-flex items-center gap-1.5 rounded-full bg-white/70 px-3 py-1 text-xs font-bold uppercase tracking-wide backdrop-blur" style={{ color: accent }}>
        <Sparkles className="h-3.5 w-3.5" /> {theme.heroKicker}
      </span>
      <h1 className={`mt-5 text-4xl font-extrabold leading-[1.05] tracking-tight text-ink-950 sm:text-5xl ${centered ? "" : "lg:text-6xl"}`}>
        {theme.heroTitle}
      </h1>
      <p className={`mt-5 text-lg leading-relaxed text-ink-700 ${centered ? "max-w-xl" : "max-w-md"}`}>
        {theme.heroSubtitle}
      </p>
      <div className={`mt-8 flex flex-wrap gap-3 ${centered ? "justify-center" : ""}`}>
        <button onClick={onShop} className="inline-flex items-center gap-2 rounded-full px-6 py-3 text-sm font-semibold text-white shadow-lg transition-transform hover:-translate-y-0.5" style={{ background: accent, boxShadow: `0 10px 30px -8px ${accent}` }}>
          Shop the collection <ArrowRight className="h-4 w-4" />
        </button>
        <a href="#story" className="inline-flex items-center gap-2 rounded-full border border-ink-950/15 bg-white/60 px-6 py-3 text-sm font-semibold text-ink-900 backdrop-blur transition-colors hover:bg-white">
          Our story
        </a>
      </div>
      <div className={`mt-8 flex items-center gap-2 text-sm text-ink-700 ${centered ? "justify-center" : ""}`}>
        <span className="flex" style={{ color: accent }}>
          {Array.from({ length: 5 }).map((_, i) => <Star key={i} className="h-4 w-4 fill-current" />)}
        </span>
        <span className="font-medium">4.9/5 from 2,400+ happy customers</span>
      </div>
    </div>
  );
}
